### ISSUE TITLE
eoxs_upgrade command

### ISSUE THREAD

**Issue by Schpidi** [EOxServer/eoxserver#134]
**Reporter: meissls
Date: 2012/04/26 10:29**

This command would allow to upgrade an existing instantiation to a newer version of EOxServer. It should be adjusted whenever somebody commits a change to trunk like:
- adding a configuration parameter
- adding something in the database model
- adding files in instances e.g. additional configurations
- <please extend>

Note that changes like changing thy syntax of a configuration parameter should never happen. Rather add a new parameter and deprecate the old one.

**Comment by constantinius** [comment]
Database migrations are now handled via Django

Configuration changes need to be done manually
