### ISSUE TITLE
alternative methods of passing passwords to CLI tools

### ISSUE THREAD

**Issue by pacesm** [EOxServer/eoxserver#182]
**Reporter: martin.paces
Date: 2012/10/25 11:00**

Some of the EOxServer's CLI tools require specification of a password. 

So far the password has been passed in plain-text as a command-line parameter. This is very insecure as other users can see the password, e.g., by the 'ps' command.

To improve the security alternative methods of password specification shall be implemented. For inspiration, see, e.g., man pages of 'openssl' command, section 'PASS PHRASE ARGUMENTS'.

**Comment by constantinius** [comment]
This is still relevant and open for storages when created from the CLI.

But when security is a concern, they can also be created using the admin client which can be secured via HTTPS.
