### ISSUE TITLE
EOxServer client fails with an empty server.

### ISSUE THREAD

**Issue by pacesm** [EOxServer/eoxserver#317]
After a clean install (no data have been registered yet) a call to `client/configuration` fails with following error:
```
Traceback:
File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/eoxserver/eoxserver/webclient/views.py" in configuration
  63.     start_time = min(o.begin_time for o in all_objects)

Exception Type: ValueError at /client/configuration/
Exception Value: min() arg is an empty sequence
```

BTW: Are these errors logged anywhere?

**Comment by constantinius** [comment]
No, general exceptions in Django views are not logged as far as I know. Should be fixed with f876a15, please test on your setup.

**Comment by constantinius** [comment]
@pacesm: Exceptions in views like this are treated as 500 - Internal Server Error, so you should see a note in your webservers error log file.

**Comment by pacesm** [comment]
@constantinius There is nothing in the Apache error log file. There is of course a record in the access log but it does not say more than 500. To get the error message on a production machine the debug mode must be turned on first and then you get it in the debug response.

**Comment by pacesm** [comment]
f876a1567d99b19f4268dc57b9d70e8a61e8f3b0 solves this issue in 0.4 branch.

**Comment by pacesm** [comment]
already fixed
