### ISSUE TITLE
WPS: getCapabilities in the autotest returns duplicate process offerings.

### ISSUE THREAD

**Issue by pacesm** [EOxServer/eoxserver#338]
This issue consists of several problems:
1. There is a possible misconfiguration in the `autotest` instance which cause 
   the components to be searched twice over the same directory tree.
2. The `getCapabilities` response should newer contain two or more processes with the same identifier, i.e., the identifier must be unique. In the `describeProcess` and `execute` operations first matched process having the desired identifier is described or executed and thus `getCapabilities` operation can safely omit the duplicates as long as the process ordering does not change.
3. There should be a check detecting and logging multiple WPS processes with the same identifier (start-up sanity check).

**Comment by pacesm** [comment]
Point 2. resolved by c00363954038578a85c0cf0d3d5d9f28b09a2177.

**Comment by Schpidi** [comment]
@pacesm are you referring to something particular in point 1. or is it just a suspicion?

**Comment by pacesm** [comment]
@Schpidi There must be a reason why the process offerings are passed twice to the code. I suspect misconfiguration of `COMPONENTS` in the `settings.py` which causes a certain path to be searched twice.

**Comment by Schpidi** [comment]
OK, thanks. Will check.

**Comment by constantinius** [comment]
Was related to old component system.
