### ISSUE TITLE
Initial time selection

### ISSUE THREAD

**Issue by Schpidi** [EOxServer/eoxserver#339]
Probably the initial time selection in the webclient shouldn't cover entire collections. However, the current version of the bundled [EOxClient](/eox-a/eoxclient) doesn't support this. 

After an update try adding `"time": "{{ start_time }}/{{ end_time }}",` in https://github.com/EOxServer/eoxserver/blob/master/eoxserver/webclient/templates/webclient/config.json#L106 and adjusting `"start_time": isoformat(end_time - timedelta(days=1)),` (or something better) in https://github.com/EOxServer/eoxserver/blob/master/eoxserver/webclient/views.py#L76.

**Comment by constantinius** [comment]
Fixed with 0eb1111
