### ISSUE TITLE
WMS Layers should be visible on "all Earths"

### ISSUE THREAD

**Issue by Schpidi** [EOxServer/eoxserver#340]
The WebClient allows infinite panning to the West and East but WMS Layers are only visible on the initial extent i.e. between -180° and 180°.

**Comment by pacesm** [comment]
I confirm this behaviour. It seems like the OL does not wrap around the coordinates to the -/+180dg bounds.
Interestingly, the DREAM client handles the dateline wrapping correctly, including the time-slider. I do not remember any specific changes addressing this issue. The version of OL might be different though. (see: https://dream.eox.at/oda)

**Comment by constantinius** [comment]
Yes, this is (was) definitely an OL version issue. In early versions of OL3 there was no "wrapping" feature, but in the current docs, I can see that they added the `wrapX` config option for the [`TileWMS` source] (http://openlayers.org/en/v3.11.2/apidoc/ol.source.TileWMS.html). Still marked as experimental, but that should be fine.
This is actually an issue of [EOxClient] (https://github.com/EOX-A/EOxClient).

**Comment by constantinius** [comment]
Fixed with 4ebfc11
