### ISSUE TITLE
WMS: What is the purpose of the `handles` attribute of a `LayerFactory` component?

### ISSUE THREAD

**Issue by pacesm** [EOxServer/eoxserver#345]
The `handles` attribute of the WMS `LayerFactory` component lists coverage types handled by this layer factory. However this information does not seem to be used anywhere. In particular, it is neither used to select the right layer factory in case of multiple layer factories handling the same layer name suffix but different types nor to issue a warning/error if an unsupported type is passed to the layer factory.
To avoid confusion, the `handles` attribute should be used for its intended purpose or to be removed as unnecessary.

**Comment by constantinius** [comment]
I removed the `handles` attributes from the factories, as they are not checked anyway.
