### ISSUE TITLE
Rectified DS WCS request crashes when range-type band name contains spaces.

### ISSUE THREAD

**Issue by pacesm** [EOxServer/eoxserver#355]
The reason is that the name is interpreted as multiple band names by the Mapserver.
For more details, see the L8 example with the 'Deep Blue' band below.

It should be noted that range-type bands have `identifier` and `name` bands and the exact difference of their meaning is unclear to me. Apparently the `name` is passed to the Mapserver while I would expect the opposite.

In any case the EOxServer should implement proper input validation and reject range types with invalid characters in the names/ids rather than crash later. 

In addition, the meaning of the  `identifier` and `name` should be clarified and documented. The render code then should reviewed and fixed if necessary.

BTW, the server responds with `400 Bad Request` while this should be rather `500 Internal Server Error` as the WCS request was perfectly correct.

L8 example ...

**mapfile:**

```
LAYER
...
METADATA
...
"wcs_band_names"  "Deep Blue Blue Green Red NIR SWIR1 SWIR2 Cirrus TIRS1 TIRS2"
```

**exception:**

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/EOxServer-0.4.1dev-py2.7.egg/eoxserver/services/views.py", line 68, in ows
    result = handler.handle(request)
  File "/usr/lib/python2.7/site-packages/EOxServer-0.4.1dev-py2.7.egg/eoxserver/services/ows/wcs/basehandlers.py", line 267, in handle
    result_set = renderer.render(params)
  File "/usr/lib/python2.7/site-packages/EOxServer-0.4.1dev-py2.7.egg/eoxserver/services/mapserver/wcs/coverage_renderer.py", line 168, in render
    raw_result = ms.dispatch(map_, request)
  File "/usr/lib/python2.7/site-packages/EOxServer-0.4.1dev-py2.7.egg/eoxserver/contrib/mapserver.py", line 135, in dispatch
    raise MapServerException(str(e), "NoApplicableCode")
MapServerException: msWCSGetCoverageMetadata20(): WCS server error. Wrong number of band names given in layer 'LC81990272013104LGN01'. Expected 10, got 11.
```

_range type:_

```
{
    "bands": [
        {
            "color_interpretation": "Undefined",
            "data_type": "UInt16",
            "definition": "http://www.opengis.net/def/property/netcdf/1.0/unsignedShort",
            "description": "Landsat/OLI Band 1 - Deep Blue - uint16",
            "identifier": "B1",
            "name": "Deep Blue",
            "nil_values": [
                {
                    "reason": "http://www.opengis.net/def/nil/OGC/0/inapplicable",
                    "value": "0"
                }
            ],
            "uom": ""
        },
        {
            "color_interpretation": "BlueBand",
            "data_type": "UInt16",
            "definition": "http://www.opengis.net/def/property/netcdf/1.0/unsignedShort",
            "description": "Landsat/OLI Band 2 - Blue - uint16",
            "identifier": "B2",
            "name": "Blue",
            "nil_values": [
                {
                    "reason": "http://www.opengis.net/def/nil/OGC/0/inapplicable",
                    "value": "0"
                }
            ],
            "uom": ""
        },
        {
            "color_interpretation": "GreenBand",
            "data_type": "UInt16",
            "definition": "http://www.opengis.net/def/property/netcdf/1.0/unsignedShort",
            "description": "Landsat/OLI Band 3 - Green - uint16",
            "identifier": "B3",
            "name": "Green",
            "nil_values": [
                {
                    "reason": "http://www.opengis.net/def/nil/OGC/0/inapplicable",
                    "value": "0"
                }
            ],
            "uom": ""
        },
        {
            "color_interpretation": "RedBand",
            "data_type": "UInt16",
            "definition": "http://www.opengis.net/def/property/netcdf/1.0/unsignedShort",
            "description": "Landsat/OLI Band 4 - Red - uint16",
            "identifier": "B4",
            "name": "Red",
            "nil_values": [
                {
                    "reason": "http://www.opengis.net/def/nil/OGC/0/inapplicable",
                    "value": "0"
                }
            ],
            "uom": ""
        },
        {
            "color_interpretation": "Undefined",
            "data_type": "UInt16",
            "definition": "http://www.opengis.net/def/property/netcdf/1.0/unsignedShort",
            "description": "Landsat/OLI Band 5 - NIR - uint16",
            "identifier": "B5",
            "name": "NIR",
            "nil_values": [
                {
                    "reason": "http://www.opengis.net/def/nil/OGC/0/inapplicable",
                    "value": "0"
                }
            ],
            "uom": ""
        },
        {
            "color_interpretation": "Undefined",
            "data_type": "UInt16",
            "definition": "http://www.opengis.net/def/property/netcdf/1.0/unsignedShort",
            "description": "Landsat/OLI Band 6 - SWIR1 - uint16",
            "identifier": "B6",
            "name": "SWIR1",
            "nil_values": [
                {
                    "reason": "http://www.opengis.net/def/nil/OGC/0/inapplicable",
                    "value": "0"
                }
            ],
            "uom": ""
        },
        {
            "color_interpretation": "Undefined",
            "data_type": "UInt16",
            "definition": "http://www.opengis.net/def/property/netcdf/1.0/unsignedShort",
            "description": "Landsat/OLI Band 7 - SWIR2 - uint16",
            "identifier": "B7",
            "name": "SWIR2",
            "nil_values": [
                {
                    "reason": "http://www.opengis.net/def/nil/OGC/0/inapplicable",
                    "value": "0"
                }
            ],
            "uom": ""
        },
        {
            "color_interpretation": "Undefined",
            "data_type": "UInt16",
            "definition": "http://www.opengis.net/def/property/netcdf/1.0/unsignedShort",
            "description": "Landsat/OLI Band 9 - Cirrus - uint16",
            "identifier": "B9",
            "name": "Cirrus",
            "nil_values": [
                {
                    "reason": "http://www.opengis.net/def/nil/OGC/0/inapplicable",
                    "value": "0"
                }
            ],
            "uom": ""
        },
        {
            "color_interpretation": "Undefined",
            "data_type": "UInt16",
            "definition": "http://www.opengis.net/def/property/netcdf/1.0/unsignedShort",
            "description": "Landsat/TIRS Band 10 - TIRS1 - uint16",
            "identifier": "B10",
            "name": "TIRS1",
            "nil_values": [
                {
                    "reason": "http://www.opengis.net/def/nil/OGC/0/inapplicable",
                    "value": "0"
                }
            ],
            "uom": ""
        },
        {
            "color_interpretation": "Undefined",
            "data_type": "UInt16",
            "definition": "http://www.opengis.net/def/property/netcdf/1.0/unsignedShort",
            "description": "Landsat/TIRS Band 11 - TIRS2 - uint16",
            "identifier": "B11",
            "name": "TIRS2",
            "nil_values": [
                {
                    "reason": "http://www.opengis.net/def/nil/OGC/0/inapplicable",
                    "value": "0"
                }
            ],
            "uom": ""
        }
    ],
    "name": "LandsatOLI_TIRS:radiance:uint16"
}
```

**Comment by constantinius** [comment]
You're right, the band `name` and `identifier` are not properly documented, but my guess is, that they are based on the types from the swe (DataRecordType is defined here: http://schemas.opengis.net/sweCommon/2.0/record_components.xsd).

The `name` is obviously used for the `name` property of the `field` structure which is defined as an `NCName`, so whitespace (and various other special characters) are not allowed to produce a valid XML according to the schemas. So IMO the render code is fine in this case but the `RangeType` (or `Band`) model should check for such values with validators and prohibit the registration.

Regarding the Error code: I guess you're right, this should be a `500`.

**Comment by pacesm** [comment]
OK, so we know that the `name` is used as the records name in SWE (which is reused by WCS to describe the coverage range) and as the band name passed to mapserver. What about the `identifier`? Is it actually used for anything?

**Comment by Schpidi** [comment]
Nice coincidence, I'm right now looking into this from a standards perspective. The OPeNDAP folks found that the limitation of the `name` attribute of `swe:field` to type `NCName` is quite an issue. Apparently NetCDF files don't have that limitation which makes it difficult to serve them via WCS as is. An idea is to use the `swe:identifier` element of type `anyURI` located under `swe:field/swe:Quantity` to store the actual ID and the `name` attribute normalized to `NCName` for WCS internals. That is a little awkward in the range subsetting extension but I don't see a better solution right now. What do you think?

**Comment by pacesm** [comment]
@Schpidi I have no deep insight into SWE to make any qualified opinion. As you describe it is seems to be the only solution within the given constraints. I am fine with it as long as each of the range-type/band parameter has a clear documented purpose.

**Comment by constantinius** [comment]
@pacesm: I checked the output XML structure and the mapserver implementation, and there is no trace of the usage of the `identifier`. Frankly, I have no idea where it is used in EOxServer and how it ended up in the data model (its there for a long time now). IMO we can drop the identifier unless we find out that its used somewhere.

Regarding the validator for the `name` property I propose the following regex: https://regexper.com/#%5E(%5Ba-zA-Z%5D%7C_)(%5Cd%7C_%7C-%7C%5C.)*
It might be stricter than the actual NCName restrictions, but I could not find a suitable regex, that covers NCName well.

**Comment by constantinius** [comment]
Okay, I just found out that in 0.3 there already was an NCName validator that we could re-use: https://github.com/EOxServer/eoxserver/blob/0.3/eoxserver/resources/coverages/models.py#L57
Regarding the `swe:identifier` we would have to be careful aswell as the anyURI is also quite strict: http://www.datypic.com/sc/xsd/t-xsd_anyURI.html

**Comment by pacesm** [comment]
@constantinius: 

OK `identifier` does not seem to be currently used. It might be then used later for the `swe:identifier`.
The anyURI allows escaping which allows to use fairly larger set of characters.

I think the NC reg-ex. should be more like `^[a-zA-Z_][a-zA-Z0-9_.-]*$` (you missed the alphabetic characters in the follow on and the line-end which would allow any ending character).

**Comment by baloola** [comment]
currently, MapServer is not used for wcs rendering, so the error does not occur.
