### ISSUE TITLE
0.5 (or 1.0?) Roadmap

### ISSUE THREAD

**Issue by constantinius** [EOxServer/eoxserver#368]
Non exhaustive list...

Discuss min versions of Python and Django
 - Looks like Python 2.7 and Django 1.11 (next LTS, to be released in April 2017)

EOxServer Versioning
 - discuss more strict implementation of SemVer (backwards compatibility, breaking changes)

Implementation Approach
 - Find common design approach

Data Models
 - support for 1D/3D (nD) Data
 - Discuss approach for storing metadata, some ideas:
   - Generic key-value table
   - Specific models for i.e SAR, OPT, LIMB, etc specific data (inheritance/separate tables)
   - Using external search engine (CouchDB, etc)

Ingestion
 - Additional Metadata 
 - SAFE registration
 - NetCDF files
 - Automatic deduction of range type

Data Rendering
 - Support for 1D/3D (nD) data
 - Generic data readers
 - WCS: move towards single renderer and away from MapServer

Configuration
 - Remove centralized component registry (#367)

EO OpenSearch

Direct Download (DS-EO/WCS)

...

**Comment by pacesm** [comment]
Please add following point to the agenda:
- discuss semantic versioning of the EOxServer (three minor versions 0.3, 0.4, 0.5 in a row with completely different APIs, should be rather 0.3, 1.0, 2.0)
- discuss managerial aspects of the proposed changes such as effort, schedule and possible impact on projects using EOxServer such as VirES. (Can we afford to rewrite the EOxServer from scratch again?)
- discuss how to make the design "right" this time so that the history does not repeat again with the "0.6 version" (How to prevent hasty hard-to-fix design decisions).

**Comment by constantinius** [comment]
Updated the issue. I agree to the versioning.

> Can we afford to rewrite the EOxServer from scratch again?

This is certainly not the intention. There are some features that require changes/additions to the currently implemented capabilities, but there is no need and no time to make a "rewrite" of EOxServer. But, of course, we have to take care that we do not break dependent projects, or at least make an upgrade as comfortable as possible.

> discuss how to make the design "right" this time so that the history does not repeat again with the "0.6 version" (How to prevent hasty hard-to-fix design decisions).

I agree. (This is what this issue is about, actually).

We can discuss here or in more specific tickets (and should summarize discussions we have in person)

**Comment by pacesm** [comment]
> This is certainly not the intention.

I hope so, nonetheless  it seems to me to go the same path as the 0.4 branch. 

> There are some features that require changes/additions to the currently implemented capabilities.

Understood. So let's talk about them.

>  but there is no need and no time to make a "rewrite" of EOxServer.

If you change the core data model and replace component system than you affect pretty much everything in the EOxServer plus you break compatibility with the dependent projects. This may possibly require a lot of effort to make things work again and not only in the EOxServer.

> But, of course, we have to take care that we do not break dependent projects, or at least make an
> upgrade as comfortable as possible.

Nice to hear but it does not make me less concerned.

**Comment by constantinius** [comment]
> I hope so, nonetheless it seems to me to go the same path as the 0.4 branch.

I'm not sure what that is supposed to mean. I guess this is related to the implementation effort from 0.3 to 0.4, right? Well, there were many, many issues related to the concepts introduced in 0.3, as a result, there was a lot of [discussion and effort](http://eoxserver.2316974.n4.nabble.com/eoxserver-future-data-models-td4640384.html) involved to resolve them. I think 0.4 is a good and stable starting point, nonetheless, there are issues that need discussion and resolving. Ignoring them wouldn't help us.

> If you change the core data model and replace component system than you affect pretty much everything in the EOxServer

I disagree. There is a lot more functionality (data reading, writing, transformation, service endpoints, GUI components, etc) involved. Sure, the component system is central, but that does not mean that everything it touches needs to be rewritten from scratch. I guess, that most of it can stay as it is.

Regarding the models: similarly, I only see them as a supportive element, not the 'core' of EOxServer. Sure, when we make changes to the models (which are necessary, when we want to implement the features mentioned above), there will be some necessary adaptions, but the most of EOxServer will be unchanged.

> plus you break compatibility with the dependent projects.

With some of the proposed changes, it will be unavoidable to introduce breaking changes. It is our obligation to decide whether or not the changes are really necessary.

> Nice to hear but it does not make me less concerned.

I understand. So we need your contribution to the proposed specific features and concepts in order to build a next version everyone is happy with.
