### ISSUE TITLE
Support of data with other dimensionality than flat 2D

### ISSUE THREAD

**Issue by constantinius** [EOxServer/eoxserver#370]
This is a summary issue to find a design and to implement support of data with other dimensionality than 2D "flat" images

The following input data shall be supported:

 * 1D data (like the ones used in the VirES project)
 * 2D data not "flatly" projected (such as "vertical curtains")
 * 3D data: 2D + height (or another axis)
 * maybe arbitrary number of dimensions?

The datasets shall be

 * registered
 * stored
 * described (via e.g WCS DescribeCoverage or Atom)
 * retrieved, allowing
   * subsetting along all axes
   * slicing: producing output data of reduced dimensionality
   * scaling along all axes
   * reprojection
 * rendered on maps, as good as possible

Common data formats dealing with these datasets shall be supported:

 * netCDF
 * CDF
 * ...

In order to achieve this new functionality, the following tasks have to be done:

 * extend the data models to support storing these datasets (see #...)
 * enhance registration mechanism to retrieve necessary metadata 
 * enhance (WCS) data rendering
   * replace MapServer
   * Implement input readers and output formats and a common intermediary exchange format (e.g numpy arrays + some metadata)
   * find a way to not impede performance for the currently supported use cases

**Comment by jankovicgd** [comment]
timeseries are now possible to register. netcdf and zarr
