### ISSUE TITLE
wrong assertion in xmltools.py

### ISSUE THREAD

**Issue by pacesm** [EOxServer/eoxserver#374]
After the recent 0.4 merges the Django commands started complaining about the wrong assertion:
```
/usr/local/eoxserver/eoxserver/core/util/xmltools.py:144: SyntaxWarning: assertion is always true, perhaps remove parentheses?
```
The actual code was added in cef1df1a5a065619473c393cf417158588f2bd75 and it does:
```
    assert (                                                                     
        not element.text,                                                        
        "Can't add a CDATA section. Element already has some text: %r"           
        % element.text                                                           
    )
```
(The tuple is always cast to `True` regardless of the tested condition.)

Please fix it to get rid of that annoying warning.

**Comment by constantinius** [comment]
Done with 2bf9ec4d9cbbdbec1fe793bd7b366db78b985922
