### ISSUE TITLE
Make sure OpenSearch correctly responds to searches crossing the dateline/antimeridian

### ISSUE THREAD

**Issue by Schpidi** [EOxServer/eoxserver#377]
bbox searches where the first value is bigger than the third are searches crossing the dateline. not sure if my install is outdated or if this needs to be fixed.

This correctly gives 10 results:
http://ows.eox.at/cite_staging/eoxserver/opensearch/collections/MER_FRS_RGB/atom/?count=0&startIndex=0&bbox=-60,-10,-20,35&start=2009-04-01T00:00:00.000Z&end=2009-12-31T00:00:00.000Z

Whereas this request with reversed 1st and 3rd coordinates shouldn't give any results:
http://ows.eox.at/cite_staging/eoxserver/opensearch/collections/MER_FRS_RGB/atom/?count=0&startIndex=0&bbox=0,-10,-80,35&start=2009-04-01T00:00:00.000Z&end=2009-12-31T00:00:00.000Z

Version is 0.4.1dev

**Comment by constantinius** [comment]
See #423
