### ISSUE TITLE
Plans to a standard license?

### ISSUE THREAD

**Issue by ppKrauss** [EOxServer/eoxserver#380]
Hi, is difficult to understand and trust any non-standard license. Ideal is to offer a  [standard OpenDefinition license](http://opendefinition.org), like any CC, MIT, etc. The [EOxServer/documentation/copyright](https://github.com/EOxServer/eoxserver/blob/0.4/documentation/copyright.rst) is not standard, so *need some "human time attention" to read and understand*, and perhaps a lawyer *to be reliable for my* or any other user.

**SUGGESTION**:  to add a comment  at `copyright.rst` or  `README.md`,   *about the  EOxServer/documentation/copyright interpretation*, noticing the most similar standard... Someting as "this copyright  text   was inspired in the XPTO standard license".

**Comment by Schpidi** [comment]
Hi @ppKrauss, EOxServer's license actually is MIT and I'd hoped that the statement "a MIT-style license" in the README.rst explains this adequately. How would you suggest to extend this statement? Thanks.

**Comment by ppKrauss** [comment]
> Hi @ppKrauss, EOxServer's license actually is MIT and I'd hoped that the statement ...

Oops, sorry (!) my "dynamic reading" did not read this ... Hum, perhaps ideal is to add a notice at `copyright.rst`...

MIT family license are for software, my problem was about image. Perhaps need also a comment about "content type".
