### ISSUE TITLE
Permission to use an image

### ISSUE THREAD

**Issue by ppKrauss** [EOxServer/eoxserver#381]
Can I use http://docs.eoxserver.org/en/stable/_images/processes_task_state.png  at https://wiki.openstreetmap.org ?

----

PS: impossible to **read your "copyright" without [transaction cost](https://en.wikipedia.org/wiki/Transaction_cost)**, please check [issue 380](https://github.com/EOxServer/eoxserver/issues/380).

**Comment by Schpidi** [comment]
Sure, given you provide proper attribution.

**Comment by ppKrauss** [comment]
Thanks!
