### ISSUE TITLE
Fixing processes tests

### ISSUE THREAD

**Issue by constantinius** [EOxServer/eoxserver#385]
The tests in the [processes tests file](https://github.com/EOxServer/eoxserver/blob/finalizing-new-models/eoxserver/resources/processes/tests.py) are currently failing which needs to be investigated.

Additionally, it needs to be decided whether they are actually still required, as the whole ATP was only used for WCS-T which is defunct since v0.3. When not, I think the tests can be disabled.

@pacesm please confirm

**Comment by pacesm** [comment]
The WCS-T (including ATP) has been dead since 0.3. I don't think it is really needed and it should have been removed already in the v0.4.

**Comment by constantinius** [comment]
Alright, thanks for the comment. I'll add a separate issue for the removal.
