### ISSUE TITLE
Fixing WCS 2.0/WCS 1.1 tests

### ISSUE THREAD

**Issue by constantinius** [EOxServer/eoxserver#386]
Some tests of the WCS 2.0/1.1 autotest suite are failing, which needs to be corrected.

Many of those are related to the binary files comparison. This is due to slight (or larger) changes in the binary structure of the files due to updated versions of MapServer or GDAL. The binary comparison method is flawed and should be replaced with other checks, e.g image statistics or metadata.

In any case, the failed tests need to be compared against the expected results (using QGIS) to determine if the response is correct. If yes, then the response can be moved to the expected folder to replace the previous result.

Other tests that fail are some coverage description tests. Here, the coverage metadata (like the grid) is allowed to deviate slightly in format or values (e.g: in floating point representation on a minor case). In those cases the expected result can be replaced by the new file. Others need to be investigated.

`gdalinfo -stats ...`

**Comment by Schpidi** [comment]
nip2 can easily be used besides visual inspection to determine differences in images. For example, just load two images and calculate the difference (Toolkits -> Math -> Arithmetic -> Substract) to see which pixels are different.

**Comment by baloola** [comment]
please take a look at the [inpection sheet](https://docs.google.com/spreadsheets/d/1esE_1hhOsGE7fZUqeSPVXMy_izp_lY-IeSHujzkd0qs/edit#gid=0).

**Comment by Schpidi** [comment]
Thanks for the effort, your suggestion seem reasonable. Just one thing maybe worth checking: Is the used interpolation method the same as the configured or requested one?

**Comment by constantinius** [comment]
This was done in various commits over time
