### ISSUE TITLE
Fixing WMS

### ISSUE THREAD

**Issue by constantinius** [EOxServer/eoxserver#387]
Currently, the WMS implementation is in the midst of the transition of v0.4 to v1.0. Currently the handlers for WMS 1.3 is the reference, and the other handlers for the other versions need to be aligned. Ideally, the functionality is extracted to a common base class and only the version specific differences are handled in the version specific handler.

Regarding the autotests for WMS, there are some tests (e.g: masked coverages) that are now not supported anymore. (as masks are now handled on Product level). It needs to be investigated whether this can be easily reproduced using the current data models.

As a last step, the autotest failures need to be checked with the expected results and eventually be replaced.

**Comment by baloola** [comment]
I have made a comparison sheet (between expected results and responses results). upon @constantinius comments I will replace the images in expected directory with the ones from responses.
https://docs.google.com/spreadsheets/d/1bZAJhMZ2Q-i9GKNzqji1vKpUFeogQvx6GEmrY5MLZlQ/edit#gid=0

**Comment by baloola** [comment]
**Autotest**
- `WMS13GetMapInvalidBoundingBoxTestCase` , `WMS13GetMapLayerNotDefinedFaultTestCase`, `WMS13GetMapInvalidCRSTestCase` and `WMS13GetMapFormatUnknownFaultTestCase`,
these tests has an fails at https://github.com/EOxServer/eoxserver/blob/finalizing-new-models/autotest/autotest_services/base.py#L613.
aslo the expected xml result should be in "/ogc:ServiceExceptionReport"   while the response  is the default `"/ows:ExceptionReport"`
