### ISSUE TITLE
Operator client

### ISSUE THREAD

**Issue by Schpidi** [EOxServer/eoxserver#4]
**Reporter: meissls
Date: 2011/02/13 17:19**

The operator client shall be the tool used by operators to configure EOxServer. It shall particular provide EO specific functionality like integrated editing of complete Datasets which is not and will not be available with the admin client.

Below is a list of things to consider. Please expand as needed.
- Configuration of EOMetadata needs update because of coherence checks between footprint and EO-O&M
- Redesign look & feel
- Implement and use !ComponentManager (see RFC 2)
- Triggering of synchronization between database and filesystem
- Integrated editing of complete Datasets, Mosaics, etc.
- Better handling of automatic flag
- ...

**Comment by constantinius** [comment]
This client is not required anymore. Use CLI/admin client instead.
