### ISSUE TITLE
S3 resources possible for coverage ?

### ISSUE THREAD

**Issue by Mikiya83** [EOxServer/eoxserver#427]
Hi
I try to use resources from an S3 data store.
MapServer can load resources in S3 thanks to VSI in GDAL, with synthax /vsis3/XXX.
But when i try to add a coverage with this synthax, i do not get error but image is empty in client. 
My TIF file pointed as coverage is in format like `/vsis3/images/XXX.tif` and its metadata file is also on S3 as `/vsis3/meta/XXX.txt`.
Metadata are because in Coverage menu, i can see GPS position and image size correctly.
A command like `gdalinfo /vsis3/images/XXX.tif` works well.

Did i missed something ? Thanks !

PS : i just try to add the same TIF locally (but with metadata on S3) and it works. So the image is ok, and metadata reading on S3 is ok, it's only a problem for reading image data on S3.

**Comment by constantinius** [comment]
Hi @Mikiya83 

Unfortunately, there is no native support of S3 in EOxServer yet (in contrast to Swift object storages which have their own native support).

You should be able, as you are already doing, use the `/vsis3/...` syntax, but that has not been tested.

First off, have you passed in the necessary access credentials to the docker container (I'm assuming) running the instance? The generalities of [`/vsis3`](https://gdal.org/user/virtual_file_systems.html#vsis3-aws-s3-files-random-reading) should apply.

I wanted, for some time now, implement native support of S3 in EOxServer, as it is the most common cloud storage system out there, but for us, there never was a direct requirement.

Please let me know whether you succeded, I'll look into the task of native support.

**Comment by Mikiya83** [comment]
Thanks for your response.
Yes i already set "vsis3" properties. Command line gdalinfo works, and metadata files in EOx works when they are registered on S3 with "/vsis3/meta/myMetaFile"  but not the image itself.
Do you need other tests ?

**Comment by constantinius** [comment]
I see.

Can you see the metadata registered in the EOxServer? (Does it actually read the metadata, or does it only access the file?)

Can you see anything in the log files? Error messages or the like?

**Comment by Mikiya83** [comment]
Yes metadata seems to be read (GPS locations are in metadata files and they are displayed in admin panel).

In logs i see a lot of map_renderer logs and an exception called many times : 

`[2019-12-20 14:24:02,214][views] DEBUG: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eoxserver/services/views.py", line 74, in ows
    result = handler.handle(request)
  File "/usr/local/lib/python2.7/dist-packages/eoxserver/services/ows/wms/basehandlers.py", line 219, in handle
    result_bytes, content_type, filename = map_renderer.render_map(map_)
  File "/usr/local/lib/python2.7/dist-packages/eoxserver/render/mapserver/map_renderer.py", line 127, in render_map
    image_obj = map_obj.draw()
  File "/usr/lib/python2.7/dist-packages/mapscript.py", line 2619, in draw
    return _mapscript.mapObj_draw(self)
MapServerError: msDrawMap(): Image handling error. Failed to draw layer named 'myS3__0'.
msDrawRasterLayerLow(): Unable to access file. Corrupt, empty or missing file '/vsis3/images/LC08_L1TP_195030_20191113_20191202_01_T1_B2.TIF' for layer 'myS3__0'. AWS_SECRET_ACCESS_KEY configuration option not defined
`

It does not found AWS SECRET ACCESS KEY but i defined it in env variable : 
`echo $AWS_SECRET_ACCESS_KEY
****mysecretkey****`

Do i have to set it anywhere else ?

**Comment by constantinius** [comment]
Okay, so MapServer is not allowing to read the credentials from the env variables, that is sad. 

> But i don't have access to the mapfile generated by EOx, right ?

If you have debug enabled, the mapfile is printed in the log. But that is not really useful, as the mapfile is dynamically created, with only the necessary files/layers added per request.

It *may* be possible to set the credentials using `gdal.SetConfigOption` in the e.g: `wsgi.py`. Maybe you can give that a try?

```
import gdal
gdal.SetConfigOption('AWS_SECRET_ACCESS_KEY', '...')
gdal.SetConfigOption('AWS_ACCESS_KEY_ID', '...')
```

Otherwise I think we are out of options and we need a proper implementation as an EOxServer backend type.

**Comment by Mikiya83** [comment]
Bingo ! I can get the image with these modifs in wsgi ! Thanks ! I can try my other tests ;)

**Comment by Mikiya83** [comment]
But ....

If i try to optimize the image like suggested in MapServer doc, even only the first step : 

`gdal_translate in.tif out.tif -co tiled=yes -co BLOCKXSIZE=512 -co BLOCKYSIZE=512`

i get an error on viewer : 

`[2019-12-20 15:55:26,624][views] DEBUG: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eoxserver/services/views.py", line 74, in ows
    result = handler.handle(request)
  File "/usr/local/lib/python2.7/dist-packages/eoxserver/services/ows/wms/basehandlers.py", line 219, in handle
    result_bytes, content_type, filename = map_renderer.render_map(map_)
  File "/usr/local/lib/python2.7/dist-packages/eoxserver/render/mapserver/map_renderer.py", line 127, in render_map
    image_obj = map_obj.draw()
  File "/usr/lib/python2.7/dist-packages/mapscript.py", line 2619, in draw
    return _mapscript.mapObj_draw(self)
MapServerError: msDrawMap(): Image handling error. Failed to draw layer named 'myModifTif__0'.
msDrawRasterLayerLow(): Unable to access file. Corrupt, empty or missing file '/vsis3/images/out_b2.tif' for layer 'myModifTif__0'. `/vsis3/images/out_b2.tif' not recognized as a supported file format.`

**Comment by constantinius** [comment]
The optimization is actually nothing out of the ordinary, so I'm surprised it fails to read the file.

Can you do a gdalinfo on the optimized file?

**Comment by Mikiya83** [comment]
I retried from scratch and i can get an "optimized" image to work partially but some part of the image is not rendered propertly (blurry of missing), i can some errors : 

`[2020-01-06 10:33:11,676][views] DEBUG: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eoxserver/services/views.py", line 74, in ows
    result = handler.handle(request)
  File "/usr/local/lib/python2.7/dist-packages/eoxserver/services/ows/wms/basehandlers.py", line 219, in handle
    result_bytes, content_type, filename = map_renderer.render_map(map_)
  File "/usr/local/lib/python2.7/dist-packages/eoxserver/render/mapserver/map_renderer.py", line 127, in render_map
    image_obj = map_obj.draw()
  File "/usr/lib/python2.7/dist-packages/mapscript.py", line 2619, in draw
    return _mapscript.mapObj_draw(self)
MapServerError: msDrawMap(): Image handling error. Failed to draw layer named 's3FirstOpti__0'.
msDrawRasterLayerGDAL_16BitClassification(): Unable to access file. GDALRasterIO() failed: GetBlockRef failed at X block offset 8, Y block offset 5
`

**Comment by Mikiya83** [comment]
I just try the same file but with /vsicurl instead of /vsis3 (but both point to the same Minio server)  and i don't get the same error, it seems ok, so maybe it's more related to Minio or S3 implementation of gdal...

**Comment by constantinius** [comment]
@Mikiya83 

Thank you for digging through this! Maybe this should be reported to the GDAL Devs?

I'll leave this issue open, as proper S3 support is definitely a plus and aimed for in the near future.
