### ISSUE TITLE
DNS setup broken for  docs.eoxserver.org -> readthedocs.org

### ISSUE THREAD

**Issue by jthurner** [EOxServer/eoxserver#431]
http://docs.eoxserver.org is hosted by readthedocs, which currently throws a Cloudflare DNS error. Current DNS records for docs.eoxserver:

```
;; ANSWER SECTION:
docs.eoxserver.org.	81310	IN	CNAME	readthedocs.org.
readthedocs.org.	274	IN	A	104.28.22.38
readthedocs.org.	274	IN	A	104.28.23.38
```
According to [rtd documentation](https://docs.readthedocs.io/en/latest/custom_domains.html#custom-domain-support), CNAME should be updated to readthedocs.io and the A records deleted. To make ssl work you also need to request a new cert by  "saving the domain in the project admin" on rtd.

**Comment by Schpidi** [comment]
Thanks for the detailed report. I've updated the DNS entry to point to readthedocs.io and hope the caches are updated soon (TTL 1 day). Meanwhile please feel free to use eoxserver.rtfd.io to get to the docs.

**Comment by jthurner** [comment]
Great! The link from the homepage and internal navigation is now working again.
