### ISSUE TITLE
Product deregistration should remove grid

### ISSUE THREAD

**Issue by Schpidi** [EOxServer/eoxserver#438]

**Comment by constantinius** [comment]
A product deregistration does not involve de-registration of associated coverages, thus does not delete grids. The grids are properly deleted in the `coverage` `deregister` subcommand:

https://github.com/EOxServer/eoxserver/blob/master/eoxserver/resources/coverages/management/commands/coverage.py#L276

**Comment by Schpidi** [comment]
The observed behavior on my instance is that the associated coverage is indeed deregistered when a product is deregistered.

**Comment by Schpidi** [comment]
I confirm that it works when deregistering a coverage though.

Interestingly deregistering a coverage gives me a nice message `INFO: Successfully deregistered coverage ` whereas deregistering a product is silent.
