### ISSUE TITLE
Cache location

### ISSUE THREAD

**Issue by Mikiya83** [EOxServer/eoxserver#443]
Hi
Sorry to spam you again !
I can't find the cache location. I see the command to sync MapCache (SQLite db) but i use an instance with Postgis. I can't find any cache in "/tmp", nor in Postgis DB and i can't find any SQLite file so i'm confused.... Does MapServer use any cache by default in EOX Server ?
If not, how can we configure it ? Thanks !

**Comment by constantinius** [comment]
MapCache is not handled directly by EOxServer. There is a command though to export the time dimension as a mapcache SQLite dimension file:
`python manage.py mapache sync`

**Comment by Mikiya83** [comment]
Thanks
So as i understand the doc, MapCache need a real webserver (like apache or nginx) so it is not used if we use the default installation (with GUnicorn), am i right ?

**Comment by constantinius** [comment]
Exactly. gunicorn only works with python applications.

**Comment by Mikiya83** [comment]
Thans for your quick responses
