### ISSUE TITLE
gunicorn won't start

### ISSUE THREAD

**Issue by Schpidi** [EOxServer/eoxserver#446]
Seems [switching directory at the end of the entrypoint script](https://github.com/EOxServer/eoxserver/blob/fc93efdca81a0f931603d367ee5df8466ff3c119/docker/eoxserver-entrypoint.sh#L56) isn't enough for gunicorn.

Cc @achtsnits

**Comment by constantinius** [comment]
Fixed with bb887e097c39699feb5cad290206e17cbcca86a8

Please verify @Schpidi
