### ISSUE TITLE
CQL filters for WCS GetCapabilities

### ISSUE THREAD

**Issue by constantinius** [EOxServer/eoxserver#451]
In order to limit the number of Coverages in Capabilities documents CQL should be used to filter the coverages entailed in the document

CQL parameter should be added to the Capabilties document in the operations.

**Comment by Schpidi** [comment]
we need to think how to handle the case that the CQL parameter hits a coverage where the visible flag is set to false. I'd like to being able to get a limited capabilities response even on non-visible coverages, e.g., via `cql=identifier='ID'`

**Comment by constantinius** [comment]
Done with 9f1860db3cb6aa3affb501a1ce59ea2be4645362

Also, the CQL parameter is added to the capabilities document.

Current implementation is as follows:
 - with no filters, only coverages that are `visible` for `wcs` are displayed in the Capabilities document
 - with filters, all matched coverages (even if not `visible`) are rendered in the document.
