### ISSUE TITLE
Opensearch listing html encoding of special characters

### ISSUE THREAD

**Issue by lubojr** [EOxServer/eoxserver#453]
If product has '+' in its ID, that character does not get HTML encoded to %2B when listing the product access services in opensearch response, but the query for wms/wcs requires it -> <a> direct links do not work. Either we should not allow '+' inside product name (replace it with something) or it should be url-encoded in listings.

**Comment by constantinius** [comment]
The `+` will be decoded as a space character, right?

**Comment by lubojr** [comment]
Conclusion, href of direct <a> links to services in OpenSearch response should be url encoded to allow direct access. -> solved in a0caa51c397aad228296b7eb321201baa5222b03 and 7cf113d3b1311430f912f79274084fcef642099b
