### ISSUE TITLE
Metadata retrieval from different products

### ISSUE THREAD

**Issue by stephankrause** [EOxServer/eoxserver#48]
**Reporter: krauses
Date: 2011/07/25 08:12**

At the moment, the EOxServer metadata handling supposes that the EO Metadata is stored in some file accompanying the coverage (EO Product). This is not always the case; e.g. for ENVISAT ASAR IMM products the metadata is contained in the data file.

So, we have to write additional metadata (and data) readers.

**Comment by constantinius** [comment]
Various metadata formats are now natively handled by EOxServer, additional ones can be added using the correct interfaces and a setting
