### ISSUE TITLE
STAC registration of metadata items regression

### ISSUE THREAD

**Issue by lubojr** [EOxServer/eoxserver#497]
In the commit https://github.com/EOxServer/eoxserver/commit/752b7de6dd821ac6e936041c23585e6afc01ba88 there was a change that the Metadata URL is parsed by urlparse instead of directly taking it from the STAC item.
Unfortunately this broke registering of all our current `prism` metadata items via stac, as they did put `#` symbols in the GSC metadata file name and we did not replace it during preprocessing (because it worked for previous versions of registrar). For example: 
```data23/OA/SP07/0.3/0e/urn:eop:SPOT:MULTISPECTRAL_1.5m:DS_SPOT7_201609121042136_FR1_FR1_FR1_FR1_W001N44_01871_5e68/0000/SP07_NAO_BUN__3_20160912T104213_20160912T104223_TOU_1234_5e68.DIMA.tar/GSC#CR#ESA#VHR_IMAGE_2015#20180309#162054.xml```
now during `register_stac_product` call gets unfortunately truncated to 
```data23/OA/SP07/0.3/0e/urn:eop:SPOT:MULTISPECTRAL_1.5m:DS_SPOT7_201609121042136_FR1_FR1_FR1_FR1_W001N44_01871_5e68/0000/SP07_NAO_BUN__3_20160912T104213_20160912T104223_TOU_1234_5e68.DIMA.tar/GSC```

Could we please use the urlparse with `fragment` part not being stripped or does this break some other usecase which triggered this change?

**Comment by constantinius** [comment]
@lubojr Can you try with this latest patch?

**Comment by lubojr** [comment]
Tested. Works fine! Thank you. Closing the issue.
