### ISSUE TITLE
Extend Opensearch Product entry with list of its coverages

### ISSUE THREAD

**Issue by lubojr** [EOxServer/eoxserver#502]
Currently the only way how to extract information about Product coverages from the Opensearch interface is from parsing the `href` from  WCS GetCoverage or DescribeCoverage offering listed:

`<owc:operation code="GetCoverage" method="GET" type="image/tiff" href="<service-url>/ows?service=WCS&amp;version=2.0.1&amp;request=GetCoverage&amp;coverageId=<coverage-id>"/>`

It would be great if we could announce additionally a list of coverage IDs as a new custom tag.

**Comment by constantinius** [comment]
done with #504
