### ISSUE TITLE
Direct HTTP access

### ISSUE THREAD

**Issue by constantinius** [EOxServer/eoxserver#508]
Add information for direct http access for each Data Item (either from the underlying storage or via the https://github.com/EOxServer/http_access app)

This HTTP href should be included in OpenSearch responses to allow building rich clients.

**Comment by lubojr** [comment]
Solved with a release [1.1.1-dev9](https://github.com/EOxServer/eoxserver/commit/38c3852d665183e3246dd0e7f12e254512b4c560) 
Opensearch lists access to coverages as `link rel="via" href="..."`
