### ISSUE TITLE
WPS 2.0 handling of ComplexData

### ISSUE THREAD

**Issue by baloola** [EOxServer/eoxserver#509]
Currently WPS 2.0 supports parsing LiteralData & BoundingBoxData parameters. However,  there is no ComplexData parsing available in pyows yet, maybe adding ComplexData parser in pyows is needed.

**Comment by lubojr** [comment]
Solved with a release [1.1.1-dev10](https://github.com/EOxServer/eoxserver/commit/a00388e4f1c7ed2365eb7d6dce7255d6e61b5a33)
