### ISSUE TITLE
Issues running docker instance

### ISSUE THREAD

**Issue by jeremyh3** [EOxServer/eoxserver#542]
Trying to get the docker instance working with the latest on Windows and Ubuntu and it fails with the same error in  both systems.

So tried pulling the docker instance:
`docker pull eoxa/eoxserver`

then ran the instance:
`docker run --rm -it -p 8000:8000 eoxa/eoxserver`

It fails to start with the attached output:
[output.txt](https://github.com/EOxServer/eoxserver/files/9890648/output.txt)

**Comment by jankovicgd** [comment]
Should be working now
